<a href="https://colab.research.google.com/github/vikranth-07/Uber_Ola_Ride_Analytics/blob/main/Uber_Ola_Analytics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import files
uploaded = files.upload()

Saving uber.csv to uber.csv

In [2]:
import pandas as pd

df = pd.read_csv("uber.csv")

df.rename(columns={
    'Date/Time': 'pickup_datetime',
    'Lat': 'pickup_latitude',
    'Lon': 'pickup_longitude',
    'Base': 'uber_base'
}, inplace=True)

df.head()

    pickup_datetime  pickup_latitude  pickup_longitude uber_base
0  4/1/2014 0:11:00          40.7690          -73.9549    B02512
1  4/1/2014 0:17:00          40.7267          -74.0345    B02512
2  4/1/2014 0:21:00          40.7316          -73.9873    B02512
3  4/1/2014 0:28:00          40.7588          -73.9776    B02512
4  4/1/2014 0:33:00          40.7594          -73.9722    B02512

In [3]:
import numpy as np

# Estimated trip distance
df['trip_distance'] = np.random.uniform(1, 20, len(df))

# Estimated fare
df['fare_amount'] = df['trip_distance'] * 25

# Driver ratings
df['driver_rating'] = np.random.uniform(3.5, 5.0, len(df))

# Vehicle type
df['vehicle_type'] = np.random.choice(
    ['Mini', 'Sedan', 'SUV'],
    len(df)
)

# Ride status
df['ride_status'] = np.random.choice(
    ['Completed', 'Cancelled'],
    len(df),
    p=[0.9, 0.1]
)

# Payment method
df['payment_method'] = np.random.choice(
    ['Cash', 'Card', 'UPI'],
    len(df)
)

In [4]:
df['pickup_datetime'] = pd.to_datetime(df['pickup_datetime'])

df['hour'] = df['pickup_datetime'].dt.hour
df['day'] = df['pickup_datetime'].dt.day_name()
df['month'] = df['pickup_datetime'].dt.month_name()

In [5]:
df.head()

,pickup_datetime,pickup_latitude,pickup_longitude,uber_base,trip_distance,fare_amount,driver_rating,vehicle_type,ride_status,payment_method,hour,day,month
0,2014-04-01 00:11:00,40.7690,-73.9549,B02512,15.782872,394.571792,3.932346,Mini,Completed,Card,0,Tuesday,April
1,2014-04-01 00:17:00,40.7267,-74.0345,B02512,15.879650,396.991258,3.731747,Sedan,Completed,Card,0,Tuesday,April
2,2014-04-01 00:21:00,40.7316,-73.9873,B02512,8.881868,222.046691,4.049462,SUV,Completed,Cash,0,Tuesday,April
3,2014-04-01 00:28:00,40.7588,-73.9776,B02512,13.693836,342.345910,4.039923,Sedan,Completed,UPI,0,Tuesday,April
4,2014-04-01 00:33:00,40.7594,-73.9722,B02512,17.688208,442.205211,4.087540,Mini,Completed,Cash,0,Tuesday,April

In [6]:
df.to_csv("cleaned_uber_data.csv", index=False)